import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import SupabaseProvider from "@/lib/SupabaseProvider";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";

const roboto = Roboto({
	weight: ["100", "300", "400", "500", "700", "900"],
	style: ["normal", "italic"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				{/* <Navbar /> */}
				<SupabaseProvider>{children}</SupabaseProvider>
			</body>
		</html>
	);
}
